### ISSUE TITLE
service: lista de participantes para la programación de reunión de evaluación en comite

### ISSUE THREAD

**Issue by wsaccaco** [Alexander230778/TP2GCPBackend#1]
en el servicio debe venir minimo: 
- id del participante
- nombre
- apellido
- correo
- cargo (si tenemos)

**Comment by Alexander230778** [comment]
Cambios en Servicios:
 - C0005G0001 - Interesado
 - C0005G0002 - Responsable
OUT
public int per_Codigo
public string per_Nombre
public string per_Email
public int value (Codigo)
public string text (Nombre - Email)

Servicios: Interesado, Responsable, LiderTecnico, Participante
